version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: expense-tracker-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expense-tracker
    ports:
      - "5432:5432"
